fix

diff --git a/.github/workflows/dependencies.yml b/.github/workflows/dependencies.yml
--- a/.github/workflows/dependencies.yml
+++ b/.github/workflows/dependencies.yml
@@ -26,7 +26,9 @@ jobs:
 
       - name: Plan Failed
         if: ${{ github.event.inputs.plan-failed == 'true' }}
-        run: echo "Plan Failed"
+        run: |
+          echo "Plan Failed"
+          exit 1
 
   approval:
     runs-on: ubuntu-latest
